# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  filesender:
    image: filesender
    build:
      context: .
      dockerfile: FileSender/Dockerfile
    ports:
      - 5000:5000
