USE [master]
GO
/****** Object:  Database [SendDb]    Script Date: 02/03/2022 17:13:32 ******/
CREATE DATABASE [SendDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SendDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SendDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SendDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SendDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SendDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SendDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SendDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SendDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SendDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SendDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SendDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [SendDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SendDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SendDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SendDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SendDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SendDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SendDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SendDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SendDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SendDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SendDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SendDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SendDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SendDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SendDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SendDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SendDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SendDb] SET RECOVERY FULL 
GO
ALTER DATABASE [SendDb] SET  MULTI_USER 
GO
ALTER DATABASE [SendDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SendDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SendDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SendDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SendDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SendDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SendDb', N'ON'
GO
ALTER DATABASE [SendDb] SET QUERY_STORE = OFF
GO
USE [SendDb]
GO
/****** Object:  Table [dbo].[FileContents]    Script Date: 02/03/2022 17:13:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FileContents](
	[FileId] [uniqueidentifier] NOT NULL,
	[FileName] [varchar](200) NOT NULL,
	[FileContent] [varbinary](max) NOT NULL,
	[FileUploadId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_FileContents] PRIMARY KEY CLUSTERED 
(
	[FileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FileUpload]    Script Date: 02/03/2022 17:13:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FileUpload](
	[Id] [uniqueidentifier] NOT NULL,
	[UploadDate] [datetime] NOT NULL,
	[ExpiryDate] [datetime] NULL,
	[IsViewed] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FileContents] ADD  DEFAULT (newid()) FOR [FileId]
GO
ALTER TABLE [dbo].[FileUpload] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[FileUpload] ADD  DEFAULT (getdate()) FOR [UploadDate]
GO
ALTER TABLE [dbo].[FileUpload] ADD  CONSTRAINT [DF_FileUpload_IsViewed]  DEFAULT ((0)) FOR [IsViewed]
GO
ALTER TABLE [dbo].[FileContents]  WITH CHECK ADD FOREIGN KEY([FileUploadId])
REFERENCES [dbo].[FileUpload] ([Id])
GO
USE [master]
GO
ALTER DATABASE [SendDb] SET  READ_WRITE 
GO

